import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import OfferTable from "@/components/offertable"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ Sidebar-Provider sorgt für den Zustand der Sidebar */}
        <SidebarProvider>
          <div className="flex min-h-screen">
            {/* ✅ Sidebar einfügen */}
            <AppSidebar />

            {/* ✅ Hauptinhalt */}
            <main className="flex-1 p-6">{children}</main>
          </div>
        </SidebarProvider>
        <OfferTable/>
      </body>
    </html>
  );
}
