import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
        <SidebarProvider>
          <div className="flex h-full w-full">
            {/* Sidebar bleibt links fixiert */}
            <AppSidebar className="w-64 flex-shrink-0" />

            {/* Hauptinhalt mit voller Breite */}
            <main className="flex-1 w-full min-h-screen p-6">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}